[package]
name = "example-low-level-rustls"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../../axum" }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
tracing = "0.1"
tracing-subscriber = "0.2"
