[package]
name = "http-redirect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.11"
axum-server = { version = "0.4.0", features = ["tls-rustls"] }
tokio = { version = "1.19.2", features = ["full"] }
tower-http = { version = "0.3.4", features = ["trace"] }
tracing = "0.1.3"
tracing-subscriber = { version = "0.3.14", features = ["env-filter", "std"] }
