[package]
name = "rust_embed_spa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.15"
mime_guess = "2.0.4"
rust-embed = "6.4.0"
tokio = { version = "1.20.1", features = ["full"] }
