[package]
name = "example-global-404-handler"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
axum = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }
tower = { version = "0.4", features = ["util"] }
tracing = "0.1"
tracing-subscriber = "0.2"
